dashboard:
  image:
    tag: 1.2
guardrails-usvc:
  image:
    tag: 1.2
llm-uservice:
  image:
    tag: 1.2
embedding-usvc:
  image:
    tag: 1.2
reranking-usvc:
  image:
    tag: 1.2
retriever-usvc:
  image:
    tag: 1.2
data-prep:
  image:
    #tag: 1.2
    tag: pre-1.3
chatqna-ui:
  image:
    tag: 1.2
nginx:
  image:
    tag: 1.2
image:
  tag: 1.2


