# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for ipexllm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

accelDevice: a770

# Configurations for OPEA microservice ipexllm
LLM_MODEL_ID: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B

# Parameter for --dtype, possible values: auto, half, float16, bfloat16, float, float32
# DTYPE: float16

# Parameter for --load-in-low-bit, possible values: 'sym_int4', 'asym_int4', 'fp6', 'fp8', 'fp8_e4m3', 'fp8_e5m2', 'fp16'
# QUANTIZATION: fp8

# Parameter for pipeline-parallel-size
# PIPELINE_PARALLEL_SIZE: 1

# Parameter for --tensor-parallel-size, must be sync with GPU resource limits
TENSOR_PARALLEL_SIZE: 1

shmSize: 16Gi
resources:
  limits:
    gpu.intel.com/i915: 1
  requests:
    cpu: 100m
    memory: 128Mi

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: intelanalytics/ipex-llm-serving-xpu
  # Uncomment the following line to set desired image pull policy if needed, as one of Always, IfNotPresent, Never.
  # pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.2.0-b16"

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

#This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # currently ipex-llm-serving-xpu needs to be run as default root user
  # readOnlyRootFilesystem: true
  # allowPrivilegeEscalation: false
  # runAsNonRoot: true
  # runAsUser: 1000
  # capabilities:
  #   drop:
  #   - ALL
  # seccompProfile:
  #   type: RuntimeDefault

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

readinessProbe:
  httpGet:
    path: /health
    port: ipexllm
  initialDelaySeconds: 5
  periodSeconds: 5
startupProbe:
  httpGet:
    path: /health
    port: ipexllm
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 120

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
# Note: Do not use (above) "replicaCount" with HPA (Chart ignores value=1 as it's k8s default)
# Note: Because HPA can sometimes change replica counts up and down rather frequently, the microservice needs to handle SIGTERM elegantly:
# - stop accepting new requests
# - handle all of its buffered requests
# - terminate after tthose have been processed
# See https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

global:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"
  # service account name to be shared with all parent/child charts.
  # If set, it will overwrite serviceAccount.name.
  # If set, and serviceAccount.create is false, it will assume this service account is already created by others.
  sharedSAName: ""
  # Install Prometheus serviceMonitor for service metrics
  monitoring: false
  # Prometheus Helm install release name for serviceMonitor
  prometheusRelease: prometheus-stack
