# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipexllm.fullname" . }}-config
  labels:
    {{- include "ipexllm.labels" . | nindent 4 }}
data:
  HUGGINGFACEHUB_API_TOKEN: {{ .Values.global.HUGGINGFACEHUB_API_TOKEN | quote}}
  HF_TOKEN: {{ .Values.global.HUGGINGFACEHUB_API_TOKEN | quote}}
  {{- if .Values.global.HF_ENDPOINT }}
  HF_ENDPOINT: {{ .Values.global.HF_ENDPOINT | quote}}
  {{- end }}
  http_proxy: {{ .Values.global.http_proxy | quote }}
  https_proxy: {{ .Values.global.https_proxy | quote }}
  no_proxy: {{ .Values.global.no_proxy | quote }}
  HF_HOME: "/tmp/.cache/huggingface"
  XDG_CONFIG_HOME: "/tmp"
  TORCHINDUCTOR_CACHE_DIR: "/tmp/pytorchinductor_cache"
