# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipexllm.fullname" . }}
  labels:
    {{- include "ipexllm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ipexllm
      protocol: TCP
      name: ipexllm
  selector:
    {{- include "ipexllm.selectorLabels" . | nindent 4 }}
