apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teirerank.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: slow
