apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tgi.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: slow
